components:
  parameters:
    header_token:
      name: Token
      description: Token identificador de la sesion de usuario
      in: header
      schema:
        $ref: 'schemas.yaml#/components/schemas/token'
      required: true
    path_username:
      name: username
      description: Username del usuario
      in: path
      schema:
        $ref: 'schemas.yaml#/components/schemas/username'
      required: true
    path_cliente_id:
      name: id_cliente
      description: Id del cliente
      in: path
      schema:
        type: number
        format: integer
      required: true