components:
  parameters:
    header_token:
      name: Token
      description: Token identificador de la sesion de usuario
      in: header
      schema:
        $ref: 'schemas.yaml#/components/schemas/token'
      required: true
    path_username:
      name: username
      description: Username del usuario
      in: path
      schema:
        $ref: 'schemas.yaml#/components/schemas/username'
      required: true
    query_cliente_nombre:
      name: nombre
      description: Cadena para buscar cliente por nombre
      in: query
      schema:
        $ref: 'schemas.yaml#/components/schemas/username'
      required: false
    cantidad_clientes:
      name: cant
      description: Cantidad de clientes a retornar
      in: query
      schema:
        type: number
        format: integer
        default: 10
      required: false
    path_cliente_id:
      name: id_cliente
      description: Id del cliente
      in: path
      schema:
        type: number
        format: integer
      required: true
    path_producto_id:
      name: id_producto
      description: Id del producto
      in: path
      schema:
        type: number
        format: integer
      required: true
    query_producto_nombre:
      name: nombre
      description: Cadena para buscar producto por nombre
      in: query
      schema:
        type: string
      required: false
    query_venta_fecha:
      name: fecha
      description: Fecha para buscar ventas
      in: query
      schema:
        type: string
        format: date
        example: 10-07-2023
      required: false
    path_venta_id:
      name: id_venta
      description: Id de la venta
      in: path
      schema:
        type: number
        format: integer
      required: true
