name: "🐋🚀Build and publish docker image"
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  DH_USERNAME: ${{ secrets.DOCKERHUB_ID }}
  DH_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build_image:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login on DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DH_USERNAME }}
          password: ${{ env.DH_PASSWORD }}

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure buildx
        uses: docker/setup-buildx-action@v1.0.0

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build project
        run: gradle build

      - name: Start buildx
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_ID }}/sharedz_b:${{ github.event.inputs.tag }},${{ secrets.DOCKERHUB_ID }}/sharedz_b:latest
          platforms: linux/amd64,linux/arm64
          push: true
