name: "🐋Build and publish docker image"
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
      external_port:
        type: number
        description: Puerto para exponer el servicio
        required: false
        default: 81
      internal_port:
        type: number
        description: Puerto interno donde corre el servicio
        required: false
        default: 8080
      deploy_on_anton:
        type: boolean
        description: Desplegar en anton
        required: true
        default: false
      deploy_digital_ocean:
        type: boolean
        description: Desplegar en Digital Ocean
        required: true
        default: false
env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

jobs:
  build_image:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login on DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.EDSON_DOCKERHUB_ID }}
          password: ${{ secrets.EDSON_DOCKERHUB_TOKEN }}

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure buildx
        uses: docker/setup-buildx-action@v1.0.0

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build project
        run: gradle build

      - name: Start buildx
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          tags: ${{ secrets.EDSON_DOCKERHUB_ID }}/sharedz_b:${{ inputs.tag }},${{ secrets.EDSON_DOCKERHUB_ID }}/sharedz_b:latest
          platforms: linux/amd64,linux/arm64
          push: true
  deploy:
    needs: build_image
    if: ${{ fromJSON(inputs.deploy_on_anton) || fromJSON(inputs.deploy_digital_ocean) }}
    uses: ./.github/workflows/deploy.yaml
    with:
      external_port: ${{ fromJSON(inputs.external_port) }}
      internal_port: ${{ fromJSON(inputs.internal_port) }}
      tag: ${{ github.event.inputs.tag }}
      deploy_on_anton: ${{ fromJSON(inputs.deploy_on_anton) }}
      deploy_digital_ocean: ${{ fromJSON(inputs.deploy_digital_ocean) }}
    secrets: inherit
