name: "🚀Deploy server"
on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
      external_port:
        type: number
        description: Puerto para exponer el servicio
        required: true
        default: 110
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
      external_port:
        type: number
        description: Puerto para exponer el servicio
        required: true
        default: 110
      deploy:
        type: boolean
        required: true
        description: d
        default: false
env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

jobs:
  deploy:
    runs-on:
      ubuntu-latest
    steps:
      - name: Deploy on server
        uses: fjogeleit/http-request-action@v1.14.2
        with:
          url: http://clayrite.ddns.net:42000/sharedz_backend?image=w3edd/sharedz_b&tag=${{ inputs.tag }}&iport=8080&eport=${{ inputs.external_port }}&privileged=0
          method: 'POST'
          timeout: 20000
          data: '{"DB_URL": "${{ env.DB_URL }}", "DB_USERNAME": "${{ env.DB_USERNAME }}", "DB_PASSWORD": "${{ env.DB_PASSWORD }}", "TOKEN_SECRET": "${{ env.TOKEN_SECRET }}"}'

