name: "🧪🤖Test Project"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

jobs:
  test_service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: gradle test
  validate_spec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout spec
        uses: actions/checkout@v2

      - name: Validate spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate api/sharedz.yaml"
